### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by aspiers** [albertyw/git-reviewers#40]
I did a fresh `pip install` and ran it, but `strace` showed it running `git shortlog -sne` in many files in the repo, and each one takes about 0.25s to complete, so on a large repo this seems to take forever.  Since there was no visible feedback, I initially assumed it had hung.

**Comment by aspiers** [comment]
Unfortunately I still see this running `git shortlog -sne -- $file` on many files.

**Comment by albertyw** [comment]
git-reviewers will run `git shortlog` on the files that you've modified (i.e. dirty).  That way, it returns reviewers that are most relevant instead of people who just contribute often to some other files in the repository.

That's assuming that you're running the most recent version of git reviewers.  `git reviewers -v` should return `0.12.2`.

**Comment by aspiers** [comment]
`git reviewers -v` shows 0.12.2, but on a clean tree I still see it iterating over every file:

```
$ strace -e execve -ff git reviewers
execve("/usr/bin/git", ["git", "reviewers"], 0x7ffca797a310 /* 311 vars */) = 0
strace: Process 7087 attached
[pid  7087] execve("/home/adam/.local/bin/git-reviewers", ["/home/adam/.local/bin/git-review"...], 0x564b0c7bb6d0 /* 311 vars */) = 0
strace: Process 7088 attached
[pid  7088] execve("/usr/lib/git/git", ["git", "diff", "master", "--name-only"], 0x7ffcffa3dc00 /* 311 vars */) = 0
strace: Process 7089 attached
strace: Process 7090 attached
strace: Process 7091 attached
[pid  7091] +++ exited with 0 +++
strace: Process 7092 attached
[pid  7090] +++ exited with 0 +++
strace: Process 7093 attached
strace: Process 7094 attached
[pid  7094] +++ exited with 0 +++
strace: Process 7095 attached
[pid  7093] +++ exited with 0 +++
strace: Process 7096 attached
[pid  7092] +++ exited with 0 +++
[pid  7095] +++ exited with 0 +++
[pid  7096] +++ exited with 0 +++
[pid  7089] +++ exited with 0 +++
[pid  7088] +++ exited with 0 +++
[pid  7087] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=7088, si_uid=1000, si_status=0, si_utime=0, si_stime=3} ---
strace: Process 7107 attached
[pid  7107] execve("/usr/lib/git/git", ["git", "shortlog", "-sne", "--", ".zuul.yaml"], 0x7ffcffa3dc00 /* 311 vars */) = 0
[pid  7107] +++ exited with 0 +++
[pid  7087] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=7107, si_uid=1000, si_status=0, si_utime=23, si_stime=3} ---
strace: Process 7134 attached
[pid  7134] execve("/usr/lib/git/git", ["git", "shortlog", "-sne", "--", "HACKING.rst"], 0x7ffcffa3dc00 /* 311 vars */) = 0
[pid  7134] +++ exited with 0 +++
[pid  7087] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=7134, si_uid=1000, si_status=0, si_utime=23, si_stime=2} ---
strace: Process 7135 attached
[pid  7135] execve("/usr/lib/git/git", ["git", "shortlog", "-sne", "--", "api-guide/source/down_cells.rst"], 0x7ffcffa3dc00 /* 311 vars */) = 0
[pid  7135] +++ exited with 0 +++
[pid  7087] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=7135, si_uid=1000, si_status=0, si_utime=23, si_stime=3} ---
strace: Process 7136 attached
[pid  7136] execve("/usr/lib/git/git", ["git", "shortlog", "-sne", "--", "api-guide/source/index.rst"], 0x7ffcffa3dc00 /* 311 vars */) = 0
[pid  7136] +++ exited with 0 +++
[pid  7087] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=7136, si_uid=1000, si_status=0, si_utime=25, si_stime=1} ---
strace: Process 7173 attached
[pid  7173] execve("/usr/lib/git/git", ["git", "shortlog", "-sne", "--", "api-guide/source/server_concepts"...], 0x7ffcffa3dc00 /* 311 vars */) = 0
[pid  7173] +++ exited with 0 +++
[pid  7087] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=7173, si_uid=1000, si_status=0, si_utime=23, si_stime=2} ---
strace: Process 7174 attached
[pid  7174] execve("/usr/lib/git/git", ["git", "shortlog", "-sne", "--", "api-ref/source/index.rst"], 0x7ffcffa3dc00 /* 311 vars */) = 0
[pid  7174] +++ exited with 0 +++
[pid  7087] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=7174, si_uid=1000, si_status=0, si_utime=25, si_stime=2} ---
strace: Process 7175 attached
[pid  7175] execve("/usr/lib/git/git", ["git", "shortlog", "-sne", "--", "api-ref/source/os-aggregates.inc"], 0x7ffcffa3dc00 /* 311 vars */) = 0
^C[pid  7175] --- SIGINT {si_signo=SIGINT, si_code=SI_KERNEL} ---
strace: Process 7086 detached
strace: Process 7087 detached
strace: Process 7175 detached

Traceback (most recent call last):
  File "/home/adam/.local/bin/git-reviewers", line 11, in <module>
    load_entry_point('git-reviewers==0.12.2', 'console_scripts', 'git-reviewers')()
  File "/home/adam/.local/lib/python3.6/site-packages/git_reviewers/reviewers.py", line 299, in main
    reviewers_list = get_reviewers(config.ignores, config.verbose)
  File "/home/adam/.local/lib/python3.6/site-packages/git_reviewers/reviewers.py", line 191, in get_reviewers
    finder_reviewers = finder().get_reviewers()
  File "/home/adam/.local/lib/python3.6/site-packages/git_reviewers/reviewers.py", line 123, in get_reviewers
    users = self.get_log_reviewers_from_file(changed)
  File "/home/adam/.local/lib/python3.6/site-packages/git_reviewers/reviewers.py", line 103, in get_log_reviewers_from_file
    git_shortlog = self.run_command(git_shortlog_command)
  File "/home/adam/.local/lib/python3.6/site-packages/git_reviewers/reviewers.py", line 32, in run_command
    process = subprocess.run(command, stdout=subprocess.PIPE)
  File "/home/adam/.pyenv/versions/3.6.1/lib/python3.6/subprocess.py", line 405, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/home/adam/.pyenv/versions/3.6.1/lib/python3.6/subprocess.py", line 823, in communicate
    stdout = self.stdout.read()
KeyboardInterrupt
```

**Comment by albertyw** [comment]
Is master not your main branch?  What is the result of `git diff master --name-only`?  git-reviewers will run `git shortlog -sne` on all the files listed.

**Comment by aspiers** [comment]
Ah no, I'm not running this on `master`.  I need to run it on a PR branch in order to determine which people to request reviews from.  Surely this is the main use case for this tool?

**Comment by albertyw** [comment]
Yes, you should be running this on a PR branch but it compares changes against your master branch.  If your local master branch is not up to date, or your master branch is not the default (some projects might use "production" or "dev" instead), then the changeset between your current PR branch and master might be huge and contain irrelevant files.

**Comment by aspiers** [comment]
Ah OK, that's the problem then.  There is no guarantee that `master` is the branch the changes are based on.  In many cases, it will be based on `origin/master` instead, and `master` could be many commits behind that.  Please could you make this configurable via a CLI option?  Since the base branch will vary per repo.

**Comment by aspiers** [comment]
Filed as #44.
