### ISSUE TITLE
installation fails due to Counter missing from collections

### ISSUE THREAD

**Issue by aspiers** [albertyw/git-reviewers#42]
```
$ pip3 install --user git+https://github.com/albertyw/git-reviewers.git                                                                                       
Collecting git+https://github.com/albertyw/git-reviewers.git                                                                                                     
  Cloning https://github.com/albertyw/git-reviewers.git to /tmp/pip-065tb0r7-build                                                                               
    Complete output from command python setup.py egg_info:                                                                                                       
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-065tb0r7-build/setup.py", line 8, in <module>
        from git_reviewers import reviewers
      File "/tmp/pip-065tb0r7-build/git_reviewers/reviewers.py", line 136, in <module>
        class FindHistoricalReviewers(FindFileLogReviewers):
      File "/tmp/pip-065tb0r7-build/git_reviewers/reviewers.py", line 137, in FindHistoricalReviewers
        def get_reviewers(self) -> typing.Counter[str]:
    AttributeError: module 'typing' has no attribute 'Counter'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-065tb0r7-build/ 
```

This happens with Python 3.5.3, but not 3.6.1.

**Comment by albertyw** [comment]
Should be fixed in c897e693a7a0b0a18edfb1b95af0de6123ae42ca

I'm guessing typing.Counter is introduced in python 3.6 so I instead converted the type hints into comments instead.
