### ISSUE TITLE
Bad error message when arc whoami fails

### ISSUE THREAD

**Issue by albertyw** [albertyw/git-reviewers#45]
```
$ git reviewers
 Exception
[cURL/7] (https://code.uberinternal.com/api/user.whoami) <CURLE_COULDNT_CONNECT> The cURL library raised an error while making a request. You may be able to find more information about this error (error code: 7) on the cURL site: http://curl.haxx.se/libcurl/c/libcurl-errors.html#CURLECOULDNTCONNECT
(Run with `--trace` for a full exception trace.)
Traceback (most recent call last):
  File "/Users/albertyw/.dotfiles/scripts/git/git-reviewers/git_reviewers/reviewers.py", line 315, in <module>
    main()
  File "/Users/albertyw/.dotfiles/scripts/git/git-reviewers/git_reviewers/reviewers.py", line 310, in main
    reviewers_list = get_reviewers(config)
  File "/Users/albertyw/.dotfiles/scripts/git/git-reviewers/git_reviewers/reviewers.py", line 205, in get_reviewers
    most_common = FindArcCommitReviewers(config) \
  File "/Users/albertyw/.dotfiles/scripts/git/git-reviewers/git_reviewers/reviewers.py", line 77, in filter_phabricator_activated
    usernames = [self.parse_phabricator(*x) for x in username_processes]
  File "/Users/albertyw/.dotfiles/scripts/git/git-reviewers/git_reviewers/reviewers.py", line 77, in <listcomp>
    usernames = [self.parse_phabricator(*x) for x in username_processes]
  File "/Users/albertyw/.dotfiles/scripts/git/git-reviewers/git_reviewers/reviewers.py", line 63, in parse_phabricator
    phab_output = json.loads(output_str)
  File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by albertyw** [comment]
Fixed in 3ac9dc3
